- hosts: "{{ host }}"
  connection: httpapi
  collections:
  - fortinet.fortios
  tasks:
   - name: Configure global attributes.
     fortios_system_global:
        vdom:  "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        system_global:
            hostname: "{{ hostname }}"
            timezone: "{{ timezone }}"
   - name: Configure NTP
     fortios_system_ntp:
        vdom:  "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        system_ntp:
            type: "custom"
            ntpsync: "enable"
            ntpserver:
             -
              id: "1"
              server: "{{ ntpserver1 }}"
             -
              id: "2"
              server: "{{ ntpserver2 }}"
