- hosts: HQ
  connection: httpapi
  collections:
  - fortinet.fortios

  tasks:
   - name: Configure global attributes.
     fortios_system_global:
        vdom:  "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        system_global:
            hostname: "{{ hostname }}"
            timezone: "{{ timezone }}"
 